name: License and README Check
on: workflow_call

jobs:
  Check-License:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh and reuse
        run: sudo apt install zsh reuse
      - name: License Check
        id: lcheck
        run: reuse lint
        continue-on-error: true
      - name: Generate Reports
        if: steps.lcheck.outcome != 'success'
        run: |
          mkdir output/
          reuse lint > output/results.txt
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: results
          path: output
      - uses: actions/download-artifact@v3.0.0
        with:
          name: results
      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: results/results.txt
  Check-README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh
        run: sudo apt install zsh
      - name: README.md Check
        run: if [ ! -f "README.md" ];then echo "missing README.md";return 1;fi
        shell: zsh {0}
  Check-README_zh_CN:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh
        run: sudo apt install zsh
      - name: README.zh_CN.md Check
        continue-on-error: true
        run: if [ ! -f "README.zh_CN.md" ]; then echo "missing README.zh_CN.md";return 1;fi
        shell: zsh {0}
