name: License and README Check
on: workflow_call

jobs:
  Check-License:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh and reuse
        run: sudo apt install zsh reuse
      - name: License Check
        id: lcheck
        run: reuse lint
        continue-on-error: true
      - name: Generate Reports
        if: steps.lcheck.outcome != 'success'
        run: echo "qaq"
  Check-README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh
        run: sudo apt install zsh
      - name: README.md Check
        run: if [ ! -f "README.md" ];then echo "missing README.md";return 1;fi
        shell: zsh {0}
  Check-README_zh_CN:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh
        run: sudo apt install zsh
      - name: README.zh_CN.md Check
        continue-on-error: true
        run: if [ ! -f "README.zh_CN.md" ]; then echo "missing README.zh_CN.md";return 1;fi
        shell: zsh {0}
