# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0

name: License and README Check
on: workflow_call

jobs:
  Check-License:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: fsfe/reuse-action@v1.2.0
  Check-README:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh
        run: sudo apt install zsh
      - name: README Check
        run: if [ ! -f "README.md" ];then echo "missing README.md";return 1;fi
        shell: zsh {0}
  Check-README.zh_CN:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Install zsh
        run: sudo apt install zsh
      - name: README_zh_CN Check
        run: if [ ! -f "README.zh_CN.md" ]; then echo "missing README.zh_CN.md";return 1;fi
        shell: zsh {0}
